baseurl      = "https://kipple.be"
title        = "Kipple"
languageCode = "en-us"
theme        = ["hello-friend-ng", "github.com/dzello/reveal-hugo"]
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Visualisations et sciences sociales"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]
[[params.social]]
  name = "gpg"
  url = "https://kipple.be/pgp.txt"
[[params.social]]
  name = "email"
  url = "mailto:olivier@kipple.be"
[[params.social]]
  name = "github"
  url = "https://github.com/GlozingNeuter"
[[params.social]]
 name = "matrix"
 url = "@kipple:matrix.matmoa.xyz"
[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Kipple"
    subtitle = "Visualization and social sciences"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd kipple/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "slides"
    name       = "Slides"
    url        = "/slides"
## Reveal
[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[[reveal_hugo.plugins]]
name = "revealD3"
source = "https://kipple.be/plugin/reveal.js-d3/reveald3.js"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
